services:
  - type: web
    name: cashflow-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://cashflow_db_6p0f_user:ya1vEPCEf5BglKX5fyWV05PrTpx6msVK@dpg-d7q858pugtpc73aq2uq0-a.oregon-postgres.render.com/cashflow_db_6p0f
      - key: INTERNAL_DATABASE_URL
        value: postgresql://cashflow_db_6p0f_user:ya1vEPCEf5BglKX5fyWV05PrTpx6msVK@dpg-d7q858pugtpc73aq2uq0-a.oregon-postgres.render.com/cashflow_db_6p0f
